config/routes.rb
Rails.application.routes.draw do
  root 'home/index#index'

  scope :home, module: :home do
    resources :registrations, only: [:new, :create]
    resources :sessions,      only: [:new, :create, :destroy]

    get '/sign_up', to: 'registrations#new', as: 'sign_up'
    get '/log_in', to: 'sessions#new', as: :log_in
    delete '/log_out', to: 'sessions#destroy', as: :log_out

    post 'oauth/callback', to: 'oauths#callback'
    get 'oauth/callback', to: 'oauths#callback'
    get 'oauth/:provider', to: 'oauths#oauth', as: :auth_at_provider
  end


  scope :dashboard, module: :dashboard do
    resources :profile,       only: [:edit, :update]
    resources :reviews,       only: [:show, :create]
    resources :cards
    resources :decks do
      put 'set_current', to: 'decks#set_current'
    end

    get '/reviews', to: 'reviews#show'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :cards, through: :decks, dependent: :destroy
  has_many :authentications, dependent: :destroy
  has_many :decks

  belongs_to :current_deck, class_name: Deck

  before_create :set_locale

  authenticates_with_sorcery! do |config|
    config.authentications_class = Authentication
  end

  accepts_nested_attributes_for :authentications

  EMAIL_REGEXP = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :password,
            length: { minimum: 3 },
            confirmation: true, if: :password
  validates :password_confirmation, presence: true,
            if: :password
  validates :name, presence: true
  validates :email, uniqueness: true,
            presence: true,
            format: { with: EMAIL_REGEXP },
            if: :email

  def random_card
    if current_deck
      current_deck.cards.random_for_review.first
    else
      cards.random_for_review.first
    end
  end

  def self.notify_pending_cards
    User.pending_cards.find_each do |user|
      CardsMailer.pending_cards_notification(user).deliver_now
    end
  end

  def self.pending_cards
    User.joins(:cards).where.not(email: nil).merge(Card.for_review).uniq
  end

  def set_locale
    self.locale = I18n.locale
  end

  def available_locales
    I18n.available_locales.map(&:to_s)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login(params[:user][:email], params[:user][:password])
      redirect_to root_path, notice: 'Добро пожаловать!'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to edit_user_path, notice: 'Данные обновленны'
    else
      flash.now[:alert] = 'Данные заполнены некорректно!'
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/views/users/_form.slim
= simple_form_for(user) do |f|
  = f.input :name,   input_html: { class: 'form-control' }
  = f.input :email, input_html: { class: 'form-control' }
  = f.input :password, input_html: { class: 'form-control' }
  = f.input :password_confirmation, input_html: { class: 'form-control' }
  = f.submit 'Регистрация', class: 'btn btn-default cards__input-submit'

  = link_to 'Login with Facebook', auth_at_provider_path(provider: :facebook)
  = link_to 'Login with Twitter', auth_at_provider_path(provider: :twitter)

app/views/users/edit.slim
= simple_form_for(current_user, url: user_path) do |f|
  = f.input :name, input_html: {class: 'form-control'}
  = f.input :email, input_html: {class: 'form-control'}
  = f.input :password, input_html: {class: 'form-control'}
  = f.input :password_confirmation, input_html: {class: 'form-control'}
  = f.submit 'Обновить', class: 'btn btn-default cards__input-submit'