config/routes.rb
Rails.application.routes.draw do
  root 'home/index#index'

  scope :home, module: :home do
    resources :registrations, only: [:new, :create]
    resources :sessions,      only: [:new, :create, :destroy]

    get '/sign_up', to: 'registrations#new', as: 'sign_up'
    get '/log_in', to: 'sessions#new', as: :log_in
    delete '/log_out', to: 'sessions#destroy', as: :log_out

    post 'oauth/callback', to: 'oauths#callback'
    get 'oauth/callback', to: 'oauths#callback'
    get 'oauth/:provider', to: 'oauths#oauth', as: :auth_at_provider
  end


  scope :dashboard, module: :dashboard do
    resources :profile,       only: [:edit, :update]
    resources :reviews,       only: [:show, :create]
    resources :cards
    resources :decks do
      put 'set_current', to: 'decks#set_current'
    end

    get '/reviews', to: 'reviews#show'
  end
end

app/models/deck.rb
class Deck < ActiveRecord::Base
  belongs_to :user
  has_many :cards

  validates :name, presence: true

  def current?
    user.current_deck == self
  end
end

app/controllers/dashboard/cards_controller.rb
class Dashboard::CardsController < ApplicationController
  before_action :require_login
  before_action :find_card, only: [:edit, :update, :destroy]

  def index
    @cards = current_user.cards
  end

  def new
    @card = Card.new
  end

  def show
  end

  def edit
  end

  def create
    @card = Card.create_card_in_deck(current_user, card_params)

    if @card.save
      redirect_to cards_path, notice: t('flash.card_created')
    else
      flash.now[:alert] = t('flash.fill_in_fields')
      render :new
    end
  end

  def update
    if @card.update(card_params)
      redirect_to cards_path, notice: t('flash.card_updated')
    else
      render :edit
    end
  end

  def destroy
    @card.destroy
    redirect_to cards_path
  end

  private

  def card_params
    params.require(:card).permit(:original_text, :translated_text, :image,
                                 :deck_name)
  end

  def find_card
    @card = Card.find(params[:id])
  end
end

app/controllers/dashboard/decks_controller.rb
class Dashboard::DecksController < ApplicationController
  before_action :find_deck, only: [:show, :edit, :update, :destroy, :set_current]

  def index
    @decks = current_user.decks
  end

  def show
  end

  def new
    @deck = Deck.new
  end

  def edit
  end

  def create
    @deck = current_user.decks.build(decks_params)

    if @deck.save
      redirect_to decks_path, notice: t('flash.deck_created')
    else
      flash.now[:alert] = t('flash.wrong_filling')
      render :new
    end
  end

  def update
    if @deck.update(decks_params)
      redirect_to decks_path, notice: t('flash.deck_updated')
    else
      render :edit
    end
  end

  def destroy
    if @deck.current?
      current_user.update_attributes(current_deck_id: nil)
    end

    @deck.destroy
    redirect_to decks_path, notice: t('flash.deck_deleted', deck: @deck.name)
  end

  def set_current
    if current_user.update_attributes(current_deck_id: @deck.id)
      redirect_to decks_path, notice: t('flash.deck_current', deck: @deck.name)
    else
      redirect_to decks_path, alert: t('flash.deck_current_error')
    end
  end

  private

  def decks_params
    params.require(:deck).permit(:name)
  end

  def find_deck
    id = params[:deck_id] || params[:id]

    @deck = Deck.find(id)
  end
end

app/controllers/dashboard/profile_controller.rb
class Dashboard::ProfileController < ApplicationController
  before_action :require_login

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to edit_profile_path, notice: t('flash.data_updated')
    else
      flash.now[:alert] = t('flash.wrong_filling')
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :locale)
  end
end

app/controllers/dashboard/reviews_controller.rb
class Dashboard::ReviewsController < ApplicationController
  before_action :require_login
  after_action { flash.discard if request.xhr? }

  def show
    @card = current_user.random_card

    respond_to do |format|
      if @card
        format.json { render json: @card }
      else
        format.json { render json: { review_done: t('review.done') } }
      end

      format.html
    end
  end

  def create
    @card = Card.find(review_params[:card_id])
    review_result = @card.check_answer(review_params[:answer], params[:time])

    case review_result
    when :correct_answer
      flash[:notice] = t('flash.review_correct_answer')
    when :typo_in_word
      flash[:remind] = t('flash.review_hint',
                         your_word: review_params[:answer],
                         expected_word: @card.original_text)
    when :wrong_answer
      flash[:alert] = t('flash.review_wrong_answer',
                        answer: review_params[:answer],
                        original: @card.original_text)
    end

    respond_to do |format|
      format.json { render json: { message: flash.to_h } }
    end
  end


  private

  def review_params
    params.permit(:card_id, :answer, :time)
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :find_deck, only: [:show, :edit, :update, :destroy, :set_current]

  def index
    @decks = current_user.decks
  end

  def show
  end

  def new
    @deck = Deck.new
  end

  def edit
  end

  def create
    @deck = current_user.decks.build(decks_params)

    if @deck.save
      redirect_to decks_path, notice: t('flash.deck_created')
    else
      flash.now[:alert] = t('flash.wrong_filling')
      render :new
    end
  end

  def update
    if @deck.update(decks_params)
      redirect_to decks_path, notice: t('flash.deck_updated')
    else
      render :edit
    end
  end

  def destroy
    if @deck.current?
      current_user.update_attributes(current_deck_id: nil)
    end

    @deck.destroy
    redirect_to decks_path, notice: t('flash.deck_deleted', deck: @deck.name)
  end

  def set_current
    if current_user.update_attributes(current_deck_id: @deck.id)
      redirect_to decks_path, notice: t('flash.deck_current', deck: @deck.name)
    else
      redirect_to decks_path, alert: t('flash.deck_current_error')
    end
  end

  private

  def decks_params
    params.require(:deck).permit(:name)
  end

  def find_deck
    id = params[:deck_id] || params[:id]

    @deck = Deck.find(id)
  end
end

app/views/dashboard/decks/_form.slim
= simple_form_for(deck) do |f|
  = f.input :name, input_html: { class: 'form-control' }
  = f.button :submit, class: 'btn btn-default cards__input-submit'

app/views/dashboard/decks/edit.slim
= render 'form', deck: @deck

app/views/dashboard/decks/index.slim
- if current_user.decks.empty?
  div class="flash flash-remind" = t('flash.deck_empty')
- elsif current_user.current_deck_id.nil?
  div class="flash flash-remind" = t('flash.deck_set_current')

div = link_to t('link.add_deck'), new_deck_path


ul class = "decks clearfix"
  - @decks.each do |deck|

      li class="decks__item bs-callout bs-callout-default"
        div
          - if deck.current?
            h4 class="decks__current" = t('deck.current')

          div class="decks__name" = deck.name

          div class="btn-group"
            = link_to t('button.show_cards'), deck_path(deck), class: 'btn btn-default'
            - unless deck.current?
              = link_to t('button.set_current'), deck_set_current_path(deck), method: :put, class: 'btn btn-default'

          div class="btn-group pull-right"
            = link_to t('button.edit'), edit_deck_path(deck), class: 'btn btn-success'
            = link_to t('button.delete'), deck_path(deck), method: :delete, class: 'btn btn-danger'

app/views/dashboard/decks/new.slim
= render 'form', deck: @deck

app/views/dashboard/decks/show.slim
ul class="cards clearfix"
  - counter = 0
  - @deck.cards.each do |card|

    li class="bs-callout bs-callout-primary"
      div class="cards__info-wrapper"
        h4 #{ t('card.name') } # #{ counter += 1 }

        div class="cards__info"
          div = image_tag card.image.thumb
          div #{ t('card.original_text') }: #{ card.original_text }
          div #{ t('card.translated_text') }:  #{ card.translated_text }
          div #{ t('card.review_date') }: #{ card.review_date.strftime("%d/%m/%Y") }

      div class="btn-group"
        = link_to t('button.edit'), edit_card_path(card), class: 'btn btn-success'
        = link_to t('button.delete'), card_path(card), method: :delete, class: 'btn btn-danger'