config/routes.rb
Rails.application.routes.draw do
  root 'home/index#index'

  scope :home, module: :home do
    resources :registrations, only: [:new, :create]
    resources :sessions,      only: [:new, :create, :destroy]

    get '/sign_up', to: 'registrations#new', as: 'sign_up'
    get '/log_in', to: 'sessions#new', as: :log_in
    delete '/log_out', to: 'sessions#destroy', as: :log_out

    post 'oauth/callback', to: 'oauths#callback'
    get 'oauth/callback', to: 'oauths#callback'
    get 'oauth/:provider', to: 'oauths#oauth', as: :auth_at_provider
  end


  scope :dashboard, module: :dashboard do
    resources :profile,       only: [:edit, :update]
    resources :reviews,       only: [:show, :create]
    resources :cards
    resources :decks do
      put 'set_current', to: 'decks#set_current'
    end

    get '/reviews', to: 'reviews#show'
  end
end

app/views/layouts/application.slim
doctype html
html
  head
    title #{ t('app.name')}
    = stylesheet_link_tag    'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  body
    section#container

      header.clearfix
        h1 = link_to t('app.name'), '/'
        ul.navigation-links
          - if current_user

            li
              = link_to t('link.all_cards'), cards_path
            li
              = link_to t('link.all_decks'), decks_path

            ul class='pull-right'
              li
                = link_to current_user.name, edit_profile_path(current_user)
              li
                = link_to t('link.log_out'), log_out_path, method: :delete

          - else
            li
              = link_to t('link.registration'), sign_up_path
            li
              = link_to t('link.log_in'), log_in_path


      section#content
        div.flash-container
          - if flash.any?
            = render 'shared/flash'
        = yield

      = render 'shared/footer'